kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hp-pv
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 100Mi
