apiVersion: v1
kind: Pod
metadata:
  labels:
    test: iscsi-pvc-pod
  name: iscsi-pv-pod1
spec:
  containers:
  - name: iscsi-pv-pod
    image: robertxie/ubuntu-nettools
    #securityContext:
    #  privileged: true
    command: ["sleep", "60000"]
    volumeDevices:
    - devicePath: /dev/block
      name: iscsi-vol1
  volumes:
  - name: iscsi-vol1
    persistentVolumeClaim:
      claimName: myclaim

